### PR TITLE
Option to execute external script/program on add/remove/change events.

### PR DESCRIPTION
**Pull request by kimmot**

### CODE REVIEW

**Comment by borine** [comment]
@kimmot Thankyou for for this pull request, however it is unlikely that I will merge it for two reasons:

1) I wrote this utility specifically for maintaining my ALSA configuration files when using BlueALSA, and am reluctant to extend it beyond that purpose (hence the choice of name `bluealsa-autoconfig`). If you have a script that applies some additional global ALSA configuration (and is generally useful to other BlueALSA users) then perhaps that could be directly integrated as an additional function within the `bluealsa-autoconfig` daemon. I would be happy to consider such a request. Similarly, if there is some common event system other than `udev` which ALSA applications use for notification of audio card events, and requires root privileges, then perhaps `bluealsa-autoconfig` could be extended to generate such events too. 

2) This daemon runs as `root` and therefore any process forked from here also runs with root privileges. I do not wish to invest effort in managing EUIDs or user privileges, and the idea of running arbitrary code as `root` is not acceptable to me. The fact is that (almost) all permisions/privileges required to use the `audio` subsystem are granted by membership of the `audio` group, so I think a daemon that runs within the session of a user who is a member of that group is the logical way to launch the type of arbitrary helper scripts that this PR seems to be proposing. And of course `systemd` can watch for file updates using `path` units, so the systemd user session can be used to start a service when the file `/var/lib/alsa/conf.d/bluealsa-autoconfig.conf` is changed by `bluealsa-autoconfig`.

Perhaps one day I will find time to write a generic bluealsa monitor daemon; the bluealsa-client code here should be a useful basis for that. But at present I am struggling to find any free time for programming, and already have a number of other mini-projects for my own personal use that are queued and waiting for my attention.

Incidentally, all the code here is MIT licensed, so you can use the files here as a basis for your own project if you wish.

**Comment by borine** [comment]
@kimmot I've just pushed an update that includes a new utility daemon `bluealsa-agent` that hopefully performs the same function as this PR, but in a new process. Does that work for you?

**Comment by kimmot** [comment]
Thanks. I was looking for a simple bluez-alsa monitoring solution such that provides connection and disconnection information including PCM path to a separate process that can then start a music player process for the device. I checked the udev implementation but that didn't provide the PCM path (and I didn't want to scan changes based on that) and that's why I made the proposed patch. And this is related to my plan to provide support for Bluetooth devices in Daphile (www.daphile.com).
If new bluealsa-agent provides this feature I'm happy to use it.
And I totally understand and appreciate your earlier comments.

**Comment by kimmot** [comment]
I have now tested new bluetooth-agent and it's working very well. Thank you! Happy to close the pull request as obsolete.

**Pull request closed without merging**
